Fix: 일기작성 시 추천문장 삭제부분 수정
Team-MoMo/MoMo-Server pull request #118
Opened 2021-03-07 16:32 UTC by yeonghyeonSeok

2021-03-07 16:42 UTC, rdd9223 requested changes
코드리뷰 부분 한번 확인 해주세요!

2021-03-07 16:42 UTC, rdd9223 commented on server/src/services/diaries_service.ts
> +      );
이부분 내가 알기로는 await 이 비동기로 돌아서 제대로 동기적으로 수행 안되는걸로 알고있는데
map이나 foreach의 비동기처리 한번 검색해보면 좋겠네요!

2021-03-07 16:44 UTC, rdd9223 commented on server/src/services/diaries_service.ts
> +      );
그리고 쿼리도 조금 확인 해봐야할듯! 조금 이상항!
```suggestion
      recommendedSentencesInfo.forEach(
        async (element) => {
          await element.destroy({ transaction });
        },
      );
```
이렇게 transaction옵션이 안에 들어가 있어야 하지 않을까

2021-03-07 16:45 UTC, yeonghyeonSeok commented on server/src/services/diaries_service.ts
> +      );
그렇게 해보니까 에러가뜨더라고 그래서 저렇게 바꿨는데 되가지고 우선 저렇게 했는데..!

2021-03-09 17:49 UTC, rdd9223 commented on server/src/services/diaries_service.ts
> +      );
아마아 트랜잭션이 안먹을텐데.......

2021-03-09 17:54 UTC, rdd9223 approved these changes
흠잡을데가 없네유

2021-03-09 17:54 UTC, rdd9223 commented on server/src/models/users_recommended_sentences_model.ts
> +      },
굿굿굿 ㅎㅎ

2021-03-09 23:46 UTC, merged