Feat: sentences API(문장 전체 조회) 구현
Team-MoMo/MoMo-Server pull request #12
Opened 2021-01-02 09:54 UTC by yeonghyeonSeok

2021-01-02 11:43 UTC, rdd9223 submitted a review, later dismissed
굯굿

2021-01-02 11:43 UTC, rdd9223 commented on src/controllers/sentences_controller.ts
>  import resMessage from '../utils/resMessage';
요놈도 합쳐주세요!!!!

2021-01-05 06:22 UTC, rdd9223 requested changes

2021-01-05 06:22 UTC, rdd9223 commented on src/controllers/sentences_controller.ts
> +  const { emotion, user }: any = req.query;
애니는 나빠요

2021-01-05 06:22 UTC, rdd9223 commented on src/controllers/sentences_controller.ts
> +  } else {
else 빼도될듯!! 습관성 else사용자

2021-01-05 06:22 UTC, rdd9223 commented on src/controllers/sentences_controller.ts
> +    await userRecommendedsentences.forEach((element) => {
forEach문은 await가 안먹힙니다!

2021-01-05 06:22 UTC, rdd9223 commented on src/services/sentences_service.ts
> +export const readAllNotInUserSentences = async (emotionId: any, userSentences: number[]) => {
우리 개발 들어가기전에는 any급하면 쓰자고 했지만 지금은 가급적 any 안써도 될듯!

2021-01-05 06:22 UTC, rdd9223 commented on src/services/sentences_service.ts
> +  });
시퀄라이즈에서 우선 랜덤으로 3개 뽑고 그다음 sort도 order에서 할 수 있을거같은데 한번 시도해볼래?

2021-01-05 06:22 UTC, rdd9223 commented on src/services/sentences_service.ts
> +    attributes: ['id', 'contents', 'writer', 'publisher', 'emotionId'],
데이터양이 무지하게 많은거나 password같이 숨겨야할 데이터가 아니면 이렇게 하나하나 attribute를 지정해줄 필요는 없음!

2021-01-05 06:22 UTC, rdd9223 commented on src/services/sentences_service.ts
> +export const readAllUsersRecommendSentencesAfter6 = async (emotionId: any, userId: any, date: dayjs.Dayjs) => {
삑 any입니다

2021-01-05 06:22 UTC, rdd9223 commented on src/services/sentences_service.ts
> +export const readAllUsersRecommendSentences = async (emotionId: any, userId: any) => {
any!

2021-01-05 06:22 UTC, rdd9223 commented on src/services/sentences_service.ts
> +export const readAllDiaries = async (emotionId: any, userId: any) => {
애니!

2021-01-05 06:22 UTC, rdd9223 commented on src/services/sentences_service.ts
>  };
bulkCreate라는 메소드가 있는데 이걸로 한번 해결해볼래?
내가 알기로는
create를 포문돌리면 DB접근 수가 많아지면서 통신속도 저하요인이 되기도 하고
bulkCreate는 한번 접근에 여러개 넣는거라 통신속도는 1번 접근이랑 근사함!

2021-01-05 06:22 UTC, rdd9223 commented on src/services/sentences_service.ts
>  };
그리고 create로 여러개를 똑같이 처리해야할거같은데 이경우는 transaction을 써야했을듯!!

2021-01-05 08:52 UTC, chaeppy reviewed
**추천 문장이 리셋되는 2가지 경우:**
1. 새벽 6시마다 리셋을 한다.
2. 일기 저장하기를 누르는 순간 추천 문장 24개가 리셋된다.

인데 이중에서
사용자가 해당 감정으로 다이어리를작성한경우는 코드에서 못찾겠는데 제가 놓친걸까요..!?!? 혹시 있다면 알랴주시면 감사하겠습니다아!! 

어려운 로직이엇는데 정말 수고 많으셧습니다~~!!!!!

2021-01-05 08:52 UTC, chaeppy commented on src/models/diaries_model.ts
> +  createdAt?: Date;
이거 자동으로 생성돼서 안넣어줘도돼 !

2021-01-05 08:52 UTC, chaeppy commented on src/models/diaries_model.ts
> +      type: DataTypes.DATE,
이거 자동으로 생성돼서 안넣어줘도돼 !

2021-01-05 08:52 UTC, chaeppy commented on src/models/users_recommended_sentences_model.ts
> +  createdAt?: Date;
이것도 ! 자동으로 생성돼서 안넣어줘도돼 !

2021-01-05 08:52 UTC, chaeppy commented on src/models/users_recommended_sentences_model.ts
> +    createdAt: {
이것도 ! 자동으로 생성돼서 안넣어줘도돼 !

2021-01-05 08:52 UTC, chaeppy commented on src/services/sentences_service.ts
> +  usersRecommendedSentences.forEach((element) => {
const usersRecommendedSentenceIds = usersRecommendedSentences.map((item)=>
 return item.sentenceId;
); 

forEach 대신에 맵으로 쓰면안되나 !?

2021-01-05 08:52 UTC, chaeppy commented on src/services/sentences_service.ts
> +  usersRecommendedSentences.forEach((element) => {
여기두 map으로 할 수 있지 않을까??

2021-01-05 08:52 UTC, chaeppy commented on src/services/sentences_service.ts
> +  userDiarySentences.forEach((element) => {
여기두!!

2021-01-05 08:52 UTC, chaeppy commented on src/controllers/sentences_controller.ts
> +    });
이게 뭘 위한 작업인지 잘 모르겠어요 !! 알려주세용!!

2021-01-05 11:51 UTC, rdd9223 submitted a review, later dismissed
스케쥴러 굿!

2021-01-05 14:02 UTC, rdd9223 approved these changes, later dismissed
수정사항 조금 제안했어! 보고 함 고쳐줘!

2021-01-05 14:02 UTC, rdd9223 commented on src/models/diaries_model.ts
> +  readonly createdAt!: string;
이건 Date로 해도 될걸??

2021-01-05 14:02 UTC, rdd9223 commented on src/services/sentences_service.ts
>  };
```suggestion
export const createUsersRecommendSentences = async (userId: number, recommendSentences: Sentence[]) => {
  await model.UsersRecommendedSentences.bulkCreate(recommendSentences.map((item) => {
  	return {
  		userId, emotionId: item.emotionId, sentenceId: item.id
  	} 
  }));
};
```
이렇게 하면 더 깔끔할것같다!

2021-01-05 14:29 UTC, rdd9223 approved these changes

2021-01-05 14:29 UTC, merged